"""add occurred time known

Revision ID: 235076f62fb6
Revises: 4dcf7bf9a8a7
Create Date: 2026-08-15 20:33:46.583242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235076f62fb6'
down_revision: Union[str, Sequence[str], None] = '4dcf7bf9a8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movement', sa.Column('occurred_time_known', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movement', 'occurred_time_known')
    # ### end Alembic commands ###
