"""add expiration date to stock movements

Revision ID: bee170a1fa4e
Revises: 235076f62fb6
Create Date: 2026-09-13 18:21:41.572633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee170a1fa4e'
down_revision: Union[str, Sequence[str], None] = '235076f62fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movement', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movement', 'expiration_date')
    # ### end Alembic commands ###
