"""create insulin and stock movement tables

Revision ID: d906d4a2157d
Revises: 
Create Date: 2026-08-15 12:39:17.027854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd906d4a2157d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insulin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('concentration_units_per_ml', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('container_volume_ml', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insulin_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('STOCK_IN', 'DOSE', 'DISCARD', 'ADJUSTMENT', name='movement_type'), nullable=False),
    sa.Column('quantity_units', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insulin_id'], ['insulin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movement')
    op.drop_table('insulin')
    # ### end Alembic commands ###
